name: build-xml
run-name: Build new XML release by @${{ github.actor }}
on:
  pull_request_target:
    types:
      - closed
jobs:
  build-xml:
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest
    steps: 
      - name: Get current date
        id: date
        run: echo "::set-output name=date::$(date +'%Y-%m-%d')"
      - name: Checkout
        uses: actions/checkout@v3
      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-verison: '18'
      - name: Clone Repo
        run: gh repo clone ${{ github.repository }}
      - name: Build XML
        run: cd .builder/
        run: npm i
        run: tsc
        run: node -r tsconfig-paths/register ./dist/main.js ${{ github.event }} ${{ secrets.DISCORD_WEBHOOK }}
        env: 
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Create release
        run: gh release create ${{ steps.date.outputs.date }} ./builder/diff.xml ./build/full.xml
        env: 
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}