name: build-xml
run-name: Build new XML release by @${{ github.actor }}
on:
  pull_request_target:
    types:
      - closed
jobs:
  build-xml:
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest
    steps: 
      - name: Get current date
        id: date
        run: echo "date=$(date +'%Y-%m-%d')" >> $GITHUB_OUTPUT
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 2
      - name: Get Diff
        id: diff
        run: git diff --name-only HEAD~1 > ./test
      - name: test
        run: ls -hal
      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: '18'
      - name: Build XMLBuilder
        run: cd .builder; npm i; tsc;
      - name: Build XML
        run: node .builder/dist/main.js "${{ steps.diff.outputs.diff}}" ${{ secrets.NOTIFICATION_WEBHOOK_URL }}
      - name: Create release
        run: gh release create ${{ steps.date.outputs.date }} ./builder/diff.xml ./build/full.xml
        env: 
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}