name: build-xml
run-name: Build new XML release by @${{ github.actor }}
on:
  pull_request_target:
    types:
      - closed
jobs:
  build-xml:
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-verison: '18'
      - run: npm i